"""crear tabla servicio

Revision ID: fbffb4012fec
Revises: 
Create Date: 2025-07-13 14:14:50.784946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbffb4012fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('kilometraje', sa.Float(), nullable=True),
    sa.Column('filtro_aceite', sa.String(length=50), nullable=True),
    sa.Column('precio_filtro_aceite', sa.Float(), nullable=True),
    sa.Column('filtro_aire', sa.String(length=50), nullable=True),
    sa.Column('precio_filtro_aire', sa.Float(), nullable=True),
    sa.Column('filtro_petroleo', sa.String(length=50), nullable=True),
    sa.Column('precio_filtro_petroleo', sa.Float(), nullable=True),
    sa.Column('aceite_motor', sa.String(length=50), nullable=True),
    sa.Column('precio_aceite_motor', sa.Float(), nullable=True),
    sa.Column('otros_1', sa.String(length=200), nullable=True),
    sa.Column('precio_otros_1', sa.Float(), nullable=True),
    sa.Column('otros_2', sa.String(length=200), nullable=True),
    sa.Column('precio_otros_2', sa.Float(), nullable=True),
    sa.Column('otros_3', sa.String(length=200), nullable=True),
    sa.Column('precio_otros_3', sa.Float(), nullable=True),
    sa.Column('otros_4', sa.String(length=200), nullable=True),
    sa.Column('precio_otros_4', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicio')
    # ### end Alembic commands ###
